"""

Revision ID: f1d6ce15229b
Revises: 
Create Date: 2021-03-20 22:50:53.995620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1d6ce15229b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(100), nullable=False),
    sa.Column('source_type', sa.String(50), nullable=False),
    sa.Column('target_type', sa.String(50), nullable=False),
    sa.Column('pipeline_type', sa.Enum('incremental', 'full_table', name='pipelinetype'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_run',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.String(100), nullable=True),
    sa.Column('status', sa.Enum('completed', 'exited', 'failed', 'running', name='pipelinestatus'), nullable=False),
    sa.Column('cloudwatch_log_stream', sa.String(200), nullable=False),
    sa.Column('started', sa.DateTime(), nullable=False),
    sa.Column('finished', sa.DateTime(), nullable=True),
    sa.Column('rows_loaded', sa.Integer(), nullable=True),
    sa.Column('start_offset', sa.String(length=100), nullable=True),
    sa.Column('end_offset', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_memory_usage',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('memory_usage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_rps',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('rps', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_rps')
    op.drop_table('pipeline_memory_usage')
    op.drop_table('pipeline_run')
    op.drop_table('pipeline')
    # ### end Alembic commands ###
