version: "3.8"
services:
  target_mysql:
    image: mariadb:10.5.8
    environment:
      MYSQL_PASSWORD: 123
      MYSQL_USER: mysql
      MYSQL_DATABASE: target
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "5306:3306"
  source_mysql:
    image: mariadb:10.5.8
    environment:
      MYSQL_PASSWORD: 123
      MYSQL_USER: mysql
      MYSQL_DATABASE: source
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "4306:3306"
